version: "3.8"

services:
    syncapod:
        context: .
        target: prod
        restart: always
        networks:
            - backend
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - db

    db:
        image: postgresql
        restart: always
        environment:
            - POSTGRES_DB=syncapod
            - POSTGRES_USER=syncapod
            - POSTGRE_PASSWORD=${db_pass}
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - backend

volumes:
    pg-data:
    syncapod-code:

networks:
    backend:
