package auth

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sschwartz96/syncapod-backend/internal/db"
)

// CreateAuthorizationCode creates and saves an authorization code with the client & user id
func (a *AuthController) CreateAuthorizationCode(ctx context.Context, userID uuid.UUID, clientID string) (*db.AuthCodeRow, error) {
	key, err := createKey(64)
	if err != nil {
		return nil, fmt.Errorf("CreateAuthorizationCode() error creating key: %v", err)
	}
	code := &db.AuthCodeRow{
		Code:     key,
		ClientID: clientID,
		UserID:   userID,
		Scope:    db.ReadChange,
	}

	err = a.oauthStore.InsertAuthCode(ctx, code)
	if err != nil {
		return nil, fmt.Errorf("AuthController.CreateAuthorizationCode() error inserting auth code: %v", err)
	}

	return code, nil
}

//// CreateAccessToken creates and saves an access token with a year of validity
//func CreateAccessToken(dbClient db.Database, authCode *models.AuthCode) (*models.AccessToken, error) {
//	tokenString, err := CreateKey(64)
//	if err != nil {
//		return nil, fmt.Errorf("error creating access token: %v", err)
//	}
//	refreshTokenString, err := CreateKey(64)
//	if err != nil {
//		return nil, fmt.Errorf("error creating access token: %v", err)
//	}
//	token := models.AccessToken{
//		AuthCode:     authCode.Code,
//		Token:        tokenString,
//		RefreshToken: refreshTokenString,
//		UserID:       authCode.UserID,
//		Created:      time.Now(),
//		Expires:      3600,
//	}
//
//	if err := dbClient.Insert(database.ColAccessToken, token); err != nil {
//		return nil, fmt.Errorf("error creating access token: %v", err)
//	}
//
//	return &token, nil
//}
//
//// ValidateAuthCode takes pointer to db client and code string, finds the code and returns it
//func ValidateAuthCode(dbClient db.Database, code string) (*models.AuthCode, error) {
//	var authCode models.AuthCode
//	err := dbClient.FindOne(database.ColAuthCode, &authCode, &db.Filter{"code": code}, nil)
//	if err != nil {
//		return nil, fmt.Errorf("ValidateAuthCode() error finding auth code: %v", err)
//	}
//	if authCode.Code == "" {
//		return nil, errors.New("not found")
//	}
//	return &authCode, nil
//}

// ValidateAccessToken takes pointer to dbclient and token string to lookup and validate AccessToken
func (a *AuthController) ValidateAccessToken(ctx context.Context, token []byte) (*db.UserRow, error) {
	user, tkn, err := a.oauthStore.GetAccessTokenAndUser(ctx, token)
	if err != nil {
		return nil, fmt.Errorf("AuthController.ValidateAccessToken() error finding token: %v", err)
	}

	// if expired
	if time.Now().After(tkn.Created.Add(time.Second * time.Duration(tkn.Expires))) {
		return nil, errors.New("AuthController.ValidateAccessToken() error: expired access token")
	}
	return user, nil
}

//func DeleteOauthAccessToken(dbClient db.Database, token string) error {
//	err := dbClient.Delete(database.ColAccessToken, &db.Filter{"token": token})
//	if err != nil {
//		return fmt.Errorf("error deleting oauth access token: %v", err)
//	}
//	return nil
//}

// createKey takes in a key length and returns base64 encoding
// of a crypo-rand generated byte sequence
func createKey(l int) ([]byte, error) {
	key := make([]byte, l)
	_, err := rand.Read(key)
	if err != nil {
		return nil, fmt.Errorf("createKey(): error creating random key: %v", err)
	}
	return key, nil
}

func encodeKey(key []byte) string {
	return base64.URLEncoding.EncodeToString(key)
}

func decodeKey(key string) ([]byte, error) {
	return base64.URLEncoding.DecodeString(key)
}
